from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Protocol
import numpy as np

@dataclass
class FrameBundle:
    raw_bgr: Optional[np.ndarray] = None
    left_preview_bgr: Optional[np.ndarray] = None
    rectified_bgr: Optional[np.ndarray] = None
    right_preview_bgr: Optional[np.ndarray] = None
    tstamp: float = 0.0

class VideoSource(Protocol):
    def open(self) -> None: ...
    def read(self) -> tuple[bool, Optional[np.ndarray]]: ...
    def fps(self) -> float: ...
    def frame_count(self) -> int: ...
    def current_index(self) -> int: ...
    def duration_seconds(self) -> float: ...
    def current_seconds(self) -> float: ...
    def close(self) -> None: ...

class PipelineStage(Protocol):
    def process(self, bundle: FrameBundle) -> FrameBundle: ...
